services:
  tabbyapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tabbyapi
    ports:
      - "5000:5000"
    environment:
      - NAME=TabbyAPI
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/app/tabbyAPI/models
      # - /path/to/config.yml:/app/config.yml               # Change me
      # - /path/to/api_tokens.yml:/app/api_tokens.yml       # Change me
    # no intel support
    # cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3