services:
  llama:
    build: 
      context: .
      dockerfile: Dockerfile   
    container_name: llama  # Specific container name
    user: "0:0"  # corre como root
    security_opt: # idem aspas
      - "label=disable"
    # monta o workspace no container
    volumes:
      - ./models:/models
    # define pasta com permissoes para instalar npm no modo rootless
    environment:
      npm_config_cache: /.npm-cache
      npm_config_prefix: /.npm-global
      LD_LIBRARY_PATH: /app:$LD_LIBRARY_PATH  # <-- IMPORTANTE!
      USER_HOME: /
      MODEL_PATH: /models/Nanbeige4.1-3B.Q4_K_M.gguf
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all,compute,graphics,video,utility
      #VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/intel_icd.json:/etc/vulkan/icd.d/nvidia_icd.json
      #VK_LOADER_DEBUG: all
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # runtime: nvidia  # em vez do deploy.resources
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        echo "=== DEBUG INFO ===" &&
        echo "HOME: $$HOME" &&
        echo "PWD: $$(pwd)" &&
        echo "USER: $$(whoami)" &&
        echo "UID: $$(id -u)" &&
        echo "MODEL_PATH: $$MODEL_PATH" &&
        echo "" &&
        echo "=== LISTANDO /home ===" &&
        ls -la /home/ &&
        echo "" &&
        echo "=== VERIFICANDO SE MODELO EXISTE ===" &&
        if [ -f "$$MODEL_PATH" ]; then
          echo "✓ Modelo encontrado: $$MODEL_PATH";
          ls -lh "$$MODEL_PATH";
        else
          echo "✗ Modelo NÃO encontrado: $$MODEL_PATH";
        fi &&
        echo "" &&
        echo "=== testa comunicacao com dev/dri ===" &&
        echo "test -w /dev/dri/renderD128 && echo 'Acesso OK' || echo 'Sem acesso'" &&
        echo "=== Confirma permissões no dev/dri ===" &&
        ls -la /dev/dri/ &&
        echo "" &&
        echo "=== INICIANDO LLAMA-SERVER ===" &&
        echo "=== SWITCHING TO USER 1000 ===" &&
        exec gosu 1000:1000 /app/llama-server
        --host 0.0.0.0
        --port 8080
        -m "$$MODEL_PATH"
        -ngl -1
        --ctx-size 100000
